---
title: "Introduction to `ggplot2`"
subtitle: "Scientific Graphics with `ggplot2` in R"
author: "Jan Boyer | jboyer@azgfd.gov"
date: "2019-07-25"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      titleSlideClass: ["left", "bottom"]
      ratio: 16:9
      highlightStyle: idea
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=4, fig.retina=3,
                      message=FALSE, warning=FALSE, cache = TRUE, 
                      autodep = TRUE, hiline=TRUE)
knitr::opts_hooks$set(fig.callout = function(options) {
  if (options$fig.callout) {
    options$echo <- FALSE
    options$out.height <- "99%"
    options$fig.width <- 16
    options$fig.height <- 8
  }
  options
})
hook_source <- knitr::knit_hooks$get('source')
knitr::knit_hooks$set(source = function(x, options) {
  if (!is.null(options$hiline) && options$hiline) {
    x <- stringr::str_replace(x, "^ ?(.+)\\s?#<<", "*\\1")
  }
  hook_source(x, options)
})
options(htmltools.dir.version = FALSE, width = 90)
as_table <- function(...) knitr::kable(..., format='html', digits = 3)

```


```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
style_mono_accent(base_color = "#43418A")
 # base_color = "#576bb5"#,
 # inverse_background_color = "#48566e",
#  code_inline_color = "#b97d58",
 # code_font_size = "0.7em",
 # padding = "1em 2em 1em 2em", 
 # text_font_size = "30px",

```

```{r load_packages_and_data, include=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(lattice)
library(palmerpenguins)


theme_set(theme_grey())
```

---
layout: true
##A Minimal ggplot

.pull-left[
```{r simpleplot_test, eval=FALSE}
ggplot(penguins) +
  aes(x = flipper_length_mm, 
      y = body_mass_g, 
      color = species) + #<<
  geom_point()
```
]

.pull-right[
```{r simpleplot_test-out, ref.label='simpleplot_test', echo=FALSE, out.width="100%"}
```
]
---